# Generated by Django 3.2.9 on 2021-11-26 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('E_book_library_management_system', '0002_book_cost'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='request',
            new_name='my_request',
        ),
    ]
