# Generated by Django 3.2.9 on 2021-12-22 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('E_book_library_management_system', '0007_alter_book_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='my_request',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
