# Generated by Django 3.2.9 on 2021-12-22 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('E_book_library_management_system', '0009_auto_20211222_2206'),
    ]

    operations = [
        migrations.CreateModel(
            name='post',
            fields=[
                ('requester', models.CharField(max_length=20)),
                ('isbn', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('post', models.TextField(max_length=200)),
            ],
        ),
    ]
