# Generated by Django 3.2.9 on 2021-12-22 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('E_book_library_management_system', '0010_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='post',
            new_name='text',
        ),
    ]
