# Generated by Django 3.2.9 on 2021-12-22 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('E_book_library_management_system', '0011_rename_post_post_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('posted_by', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=20)),
                ('author', models.CharField(max_length=20)),
                ('text', models.TextField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='post',
        ),
    ]
