# Generated by Django 3.2.9 on 2021-12-23 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('E_book_library_management_system', '0012_auto_20211223_0042'),
    ]

    operations = [
        migrations.CreateModel(
            name='book_log',
            fields=[
                ('isbn', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('author', models.CharField(max_length=20)),
                ('user_name', models.CharField(max_length=20)),
                ('date_time', models.DateTimeField()),
            ],
        ),
    ]
