# Generated by Django 3.2.9 on 2021-12-24 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('E_book_library_management_system', '0015_alter_report_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='Id',
        ),
        migrations.AddField(
            model_name='report',
            name='review_Id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
