# Generated by Django 3.2.9 on 2021-12-24 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('E_book_library_management_system', '0020_auto_20211224_2051'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log_of_report',
            name='rev_id',
        ),
        migrations.AddField(
            model_name='log_of_report',
            name='id',
            field=models.IntegerField(default='Null', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='log_of_report',
            name='author',
            field=models.CharField(default='Null', max_length=20),
        ),
        migrations.AlterField(
            model_name='log_of_report',
            name='name',
            field=models.CharField(default='Null', max_length=20),
        ),
        migrations.AlterField(
            model_name='log_of_report',
            name='posted_by',
            field=models.CharField(default='Null', max_length=20),
        ),
        migrations.AlterField(
            model_name='log_of_report',
            name='repoter',
            field=models.CharField(default='Null', max_length=20),
        ),
        migrations.AlterField(
            model_name='log_of_report',
            name='text',
            field=models.TextField(default='Null', max_length=200),
        ),
    ]
