# Generated by Django 3.2.9 on 2021-12-24 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('E_book_library_management_system', '0022_auto_20211224_2055'),
    ]

    operations = [
        migrations.DeleteModel(
            name='log_of_report',
        ),
        migrations.AddField(
            model_name='review',
            name='date_time',
            field=models.DateTimeField(default='NULL'),
        ),
    ]
