# Generated by Django 3.2.9 on 2021-12-24 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('E_book_library_management_system', '0023_auto_20211224_2101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='date_time',
        ),
    ]
