# Generated by Django 3.2.9 on 2021-12-24 15:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('E_book_library_management_system', '0029_alter_review_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='date_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
