# Generated by Django 3.2.9 on 2021-12-24 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('E_book_library_management_system', '0034_auto_20211224_2142'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='repoter',
            new_name='reporter',
        ),
    ]
