# Generated by Django 3.2.9 on 2021-12-31 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('E_book_library_management_system', '0037_auto_20211231_2320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='https://i.stack.imgur.com/l60Hf.png', upload_to='profile_pic/'),
        ),
    ]
