# Generated by Django 3.2.9 on 2022-01-02 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('E_book_library_management_system', '0040_auto_20220102_0113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='profile_pic/default.png', upload_to='profile_pic/'),
        ),
    ]
