# Generated by Django 3.2.9 on 2022-01-05 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('E_book_library_management_system', '0041_alter_profile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paid_by', models.CharField(max_length=20)),
                ('account_num', models.CharField(max_length=20)),
                ('amount', models.CharField(max_length=20)),
                ('payment_method', models.TextField(max_length=200)),
                ('date_time', models.DateTimeField()),
            ],
        ),
    ]
